namespcae: dev

services:
  config-server:
    image:
      tag: d9c79bb

  discovery-server:
    image:
      tag: d9c79bb

  admin-server:
    image:
      tag: d9c79bb

  customers-service:
    image:
      tag: d9c79bb

  visits-service:
    image:
      tag: d9c79bb

  vets-service:
    image:
      tag: d9c79bb

  genai-service:
    image:
      tag: d9c79bb

  api-gateway:
    image:
      tag: d9c79bb
